name: weather_app

on: push

jobs:
  set_up:
    runs-on: ubuntu-latest
    steps:
   
      - uses: actions/checkout@v4 
      
      - name: install python
        uses: actions/setup-python@v3
        with:
         python-version: "3.10"
      - name: install dependences
        run: |
         python -m pip install --upgrade pip
         pip install flask requests 


      - name: build docker 
        run: docker build -t weather-app .

      - name: run docker
        run: docker run -d -p 5000:5000 --name weather-app weather-app
    
