name: test-app
on: 
  push
  
jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.10"
        
      - name: install dependancies
        run: |
          pip install flask requests pytest
          pytest "unit_test.py"
      
      
      - name: unit test report
        run: |
         if pytest -q unit_Test.py; then
             echo " unit test sucess";
         else
             echo "unit test faild"
             exit 1
         fi
         
            
          
  
  
    
  
    
